spring:
  datasource:
    url: jdbc:mysql://139.198.189.177:3306/blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: bigdata

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: warn
    com.anvna.blog: info
  file:
    path: log-pro/blog.log

server:
  port: 8081